language: node_js
node_js:
  - 11.10.1
env:
  global:
    - REACT_APP_REMOTE_STORAGE_URI=https://galapagotchi.run/api
before_install:
  - openssl aes-256-cbc -K $encrypted_9dcca22fbdaa_key -iv $encrypted_9dcca22fbdaa_iv
    -in deploy-key.enc -out deploy-key -d
  - mv deploy-key ~/.ssh/id_rsa
install:
  - cd fabric/
  - yarn
  - cd ..
  - cd client/
  - yarn
  - cd ..
  - cd server/
  - yarn
  - cd ..
script:
  - cd fabric/
  - yarn asbuild:optimized
  - cd ..
  - cd client/
  - yarn build
  - cd ..
after_success:
  - scp -r client/build galapagotchi@galapagotchi.run:/home/galapagotchi/app/client/build
  - ssh "cd /home/galapagotchi/app/server && pm2 restart all"
