language: node_js
node_js:
  - 11.10.1
env:
  global:
    - REACT_APP_REMOTE_STORAGE_URI=https://galapagotchi.run/api
before_install:
  - openssl aes-256-cbc -K $encrypted_9dcca22fbdaa_key -iv $encrypted_9dcca22fbdaa_iv
    -in deploy-key.enc -out deploy-key -d
  - mv deploy-key ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
# TODO: tests
script:
  - echo "Skipping tests"
after_success:
  - ./deploy-remote.sh
