[package]
name = "eig"
version = "0.1.0"
authors = ["Gerald de Jong <geralddejong@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
nalgebra = "0.19.0"
fast_inv_sqrt = "~1.0"

[lib]
crate-type = ["cdylib", "rlib"]
