[package]
name = "eig"
version = "0.1.0"
authors = ["Gerald de Jong <geralddejong@gmail.com>"]
edition = "2018"

[dependencies]
vec3 = "0.2.1"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]
